server/payment/urls.py
from django.urls import path
from .views import completePayment

app_name = 'payment'
urlpatterns = [
    path('paymentstatus/', completePayment, name='completePayment'),
]

server/server/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/auth/', include('users.urls')),
    path('api/location/', include('locations.urls')),
    path('api/ticket/', include('tickets.urls')),
    path('api/payment/', include('payment.urls')),
]

server/tickets/urls.py
from django.urls import path
from .views import bookTicket, book_Ticket

app_name = 'ticket'

urlpatterns = [
    path('bookticket/', bookTicket, name='bookTicket'),
    path('bookticket/<int:locationID>/', book_Ticket, name='book_Ticket'),
]

server/users/urls.py
from django.urls import path

from .views import (login, logout, private, refresh, register, reset_password,
                    resetpasssord, test)

urlpatterns = [
    path('login/', login, name='login'),
    path('register/', register),
    path('private/', private),
    path('refresh/', refresh),
    path('reset/<str:token>/<int:userId>/', reset_password),
    path('resetPassword/', resetpasssord),
    path('logout/', logout),
    path('test/<int:testNo>/', test),
]

server/payment/models.py
from django.db import models
from tickets.models import Ticket

# Create your models here.


class Payment(models.Model):
    payment_request_id = models.CharField(max_length=150)
    payment_id = models.CharField(max_length=150)
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE)
    response = models.TextField(max_length=1000)

server/tickets/models.py
from django.db import models
from users.models import User
from locations.models import Location
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.


class Ticket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    date = models.DateField(null=False)
    quantity = models.IntegerField(default=1, null=False, validators=[
        MaxValueValidator(6),
        MinValueValidator(1)
    ]
    )
    amount = models.IntegerField(default=0)
    payment_id = models.CharField(
        max_length=100, default='sbcsndicjasidnckasbndckasndciuj')
    paid = models.BooleanField(default=False)

    def __str__(self) -> str:
        return (str(self.id)+"_"+self.user.username+"_"+self.location.name+"_"+str(self.paid))

server/payment/views.py
from django.shortcuts import render
from rest_framework.response import Response
from django.views.decorators.csrf import csrf_exempt
from rest_framework.decorators import api_view
from .models import Payment
from django.http import HttpResponse
from tickets.models import Ticket
from instamojo_wrapper import Instamojo
from django.conf import settings
import cloudinary
import cloudinary.uploader
import cloudinary.api
from users.utils import send_qrcode

from django.core.mail import send_mail
from django.template.loader import render_to_string
# Create your views here.

app_name = "payment"

# Completing the payment request,saving a Payment instance and sending a email with QR code


@api_view(['GET'])
def completePayment(request):
    payment_request_id = request.GET.get('payment_request_id')
    payment_status = request.GET.get('payment_status')
    payment_id = request.GET.get('payment_id')
    ticket = Ticket.objects.get(payment_id=payment_request_id)

    # Creating a client to verify payment request.
    client = Instamojo(api_key=settings.API_KEY,
                       auth_token=settings.AUTH_TOKEN,
                       endpoint='https://test.instamojo.com/api/1.1/')
    response = client.payment_request_payment_status(
        payment_request_id, payment_id)
    print(response)

    # Checking if payment has been successfully completed
    if (payment_status == 'Credit' and response['payment_request']['status'] == 'Completed'):
        ticket.paid = True
        ticket.save()
        payment = Payment(payment_request_id=payment_request_id,
                          payment_id=payment_id, ticket=ticket, response=response)
        payment.save()

        user = ticket.user

        config = cloudinary.config(secure=True)

        # Creating a payment response for QRcode
        payment_response = {
            'user_id': user.id,
            'ticket_id': ticket.id,
            'quantity': ticket.quantity,
            'order_id': payment_request_id,
            'payment_id': payment_id,
        }

        # Using a API for QR code generation
        link = "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=" + \
            str(payment_response)
        # Sending a mail
        msg_plain = render_to_string('email.txt')
        msg_html = render_to_string(
            'confirmationEmail.html', {'date': ticket.date, 'location': ticket.location, 'link': link})

        send_mail("Confirmation email",
                  msg_plain,
                  settings.EMAIL_HOST_USER,
                  [user.email],
                  html_message=msg_html)

        # send_qrcode(user.email, link)

        #Rendering successfull payment page
        return render(request, 'success.html')
    else:
        return HttpResponse("Sone error occured. Payment not successful any money deducted will be refunded within 24hrs")

server/tickets/views.py
from django.shortcuts import render

from rest_framework.response import Response
from rest_framework.decorators import api_view
from users.models import User
from locations.models import Location
from .serializers import TicketSerializer
from .models import Ticket
from django.conf import settings

# Create your views here.
from instamojo_wrapper import Instamojo


@api_view(['GET', 'POST'])
def bookTicket(request):
    if request.method == "POST":
        data = ({
            'user': User.objects.get(username=request.POST.get('user')).pk,
            'location': Location.objects.get(name=request.POST.get('location')).pk,
            'date': request.POST.get('date'),
            'quantity': request.POST.get('quantity'),
            # 'amount': request.POST.get('amount'),
        })
        ticket = TicketSerializer(data=data)
        if ticket.is_valid():
            # ticket.save()
            # Getting all the items from the frontend after validation
            user = User.objects.get(username=request.POST.get('user'))
            location = Location.objects.get(name=request.POST.get('location'))
            date = request.POST.get('date')
            quantity = request.POST.get('quantity')
            # amount = request.POST.get('amount')
            amount = int(quantity)*40
            print(amount)

            # Creating Instamojo Client and Order id
            client = Instamojo(api_key=settings.API_KEY, auth_token=settings.AUTH_TOKEN,
                               endpoint='https://test.instamojo.com/api/1.1/')

            payment_response = client.payment_request_create(
                amount=amount,
                purpose='Buying a ticket',
                buyer_name=user.username,
                email=user.email,
                send_email=True,
                redirect_url='http://localhost:8000/api/payment/paymentstatus/'
            )
            print(payment_response)
            order_id = payment_response['payment_request']['id']
            tempTicket = Ticket.objects.get_or_create(user=user, location=location,
                                                      date=date, quantity=quantity, amount=amount, payment_id=order_id)

            return render(request, 'form.html', {'payment_url': payment_response['payment_request']['longurl'], 'button': "hide-button", 'field': "disable-field"})

        return Response(ticket.errors)
    else:
        print("here")
        print(request.GET)
        id = request.GET.get("locationID")
        print(id)
        if id is None:
            return render(request, 'form.html', {'button': "", 'field': ""})
        else:
            location = Location.objects.get(id=request.GET.get("locationID"))
            return render(request, 'form.html', {"locationName": location.name, 'button': "", 'field': ""})
        # return render(request, 'form.html', {'button': "", 'field': ""})


@api_view(['GET', 'POST'])
def book_Ticket(request, locationID):
    if request.method == "POST":
        data = ({
            'user': User.objects.get(username=request.POST.get('user')).pk,
            'location': Location.objects.get(name=request.POST.get('location')).pk,
            'date': request.POST.get('date'),
            'quantity': request.POST.get('quantity'),
            # 'amount': request.POST.get('amount'),
        })
        ticket = TicketSerializer(data=data)
        if ticket.is_valid():
            # ticket.save()
            # Getting all the items from the frontend after validation
            user = User.objects.get(username=request.POST.get('user'))
            location = Location.objects.get(name=request.POST.get('location'))
            date = request.POST.get('date')
            quantity = request.POST.get('quantity')
            # amount = request.POST.get('amount')
            amount = int(quantity)*40
            print(amount)

            # Creating Instamojo Client and Order id
            client = Instamojo(api_key=settings.API_KEY, auth_token=settings.AUTH_TOKEN,
                               endpoint='https://test.instamojo.com/api/1.1/')

            payment_response = client.payment_request_create(
                amount=amount,
                purpose='Buying a ticket',
                buyer_name=user.username,
                email=user.email,
                send_email=True,
                redirect_url='http://localhost:8000/api/payment/paymentstatus/'
            )
            print(payment_response)
            order_id = payment_response['payment_request']['id']
            tempTicket = Ticket.objects.get_or_create(user=user, location=location,
                                                      date=date, quantity=quantity, amount=amount, payment_id=order_id)

            return render(request, 'form.html', {'payment_url': payment_response['payment_request']['longurl'], 'button': "hide-button", 'field': "disable-field"})

        return Response(ticket.errors)
    else:
        if locationID is None:
            return render(request, 'form.html', {'button': "", 'field': ""})
        else:
            location = Location.objects.get(pk=locationID)
            print(location)
            return render(request, 'form.html', {"locationName": str(location.name), 'button': "", 'field': ""})
        # return render(request, 'form.html', {'button': "", 'field': ""})

server/tickets/templates/form.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <style>
        .formdiv {
            margin: 50px;
            display: flex;
            flex-direction: column;
            /* align-items: center;
            justify-content: center; */
        }

        .success {
            font-size: larger;
            color: chartreuse;
        }

        .error {
            font-size: larger;
            color: red;
        }

        .messages {
            text-align: center;
        }

        .hide-button{
            display:none;
        }

        .disable-field{
            pointer-events:none;
            background:grey;
        }
    </style>

</head>

<body class="bg-dark">
    <div class="formdiv">
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li type="none" class="{{ message.tags }}"> {{ message }} </li>
            {% endfor %}
        </ul>
        {% endif %}

        <form method="post" action="{% url 'ticket:bookTicket' %}">
            <h1>{{locationName}}</h1>
            <div class="col-md-8" style="padding: 10px;color: aliceblue;">
                <label for="validationDefault01" class="form-label">User Name</label>
                <input type="text" name="user" class="form-control {{field}}" id="validationDefault01" placeholder="Eg.SachitS"
                    required>
            </div>
            {% if locationName %}
            <div class="col-md-12" style="padding: 10px;color: aliceblue;">
                <label for="validationDefault03" class="form-label">Location Name</label>
                <input type="text" name="location" class="form-control {{field}}" id="validationDefault03" placeholder="Eg.Taj Mahal"
                    value="{{locationName}}" readonly>
            </div>
            {% else %}
            <div class="col-md-12" style="padding: 10px;color: aliceblue;">
                <label for="validationDefault03" class="form-label">Location Name</label>
                <input type="text" name="location" class="form-control {{field}}" id="validationDefault03" placeholder="Eg.Taj Mahal"
                    required>
            </div>

            {% endif %}
            <div class="col-md-12" style="padding: 10px;color: aliceblue;">
                <label for="validationDefault02" class="form-label">Quantity</label>
                <input type="number" name="quantity" class="form-control {{field}}" id="validationDefault02"
                    placeholder="Max quantity is 6" required>
            </div>
            {% csrf_token %}
            <div class="col-md-4" style="padding: 10px;color: aliceblue;">
                <label for="validationDefault01" class="form-label">Date</label>
                <input type="date" name="date" class="form-control {{field}}" id="validationDefault01" placeholder="Date" required>
            </div>

            <!-- #{% comment %} <div class="col-md-12" style="padding: 10px;color: aliceblue;">
                                                                         //   <label for="validationDefault02" class="form-label">Amount</label>
                                                                          //  <input type="number" name="amount" class="form-control {{class-field}}" id="validationDefault02"
                                                                          //      placeholder="Location Description" required>
                                                                        //</div> {% endcomment %} -->
            <br>
            <div class="col-12">
                <button class="btn btn-success {{button}}" type="submit">Submit form</button>
            </div>
        </form>
        {% if payment_url %}
        <form action="{{payment_url}}" method="GET">
            <button class="btn btn-success" id="rzp-button1">Pay</button>
        </form>
        {% endif %}

        <!-- <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
        </form>
        <div class="col-12">
            <button class="btn btn-primary" type="submit">Submit form</button>
        </div> -->

    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
<script>
    function addClass() {
        var v = document.getElementById("submit-button");
        v.className += "hide-button";
    }
</script>
</body>

</html>

server/tickets/templates/payment.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Payment</title>
</head>

<body>
    <form action="{{payment_url}}" method="GET">
        <button id="rzp-button1">Pay</button>
    </form>
</body>

</html>