server/locations/urls.py
from django.urls import path
from locations.views import newLocation, viewLoc

app_name = 'locations'
urlpatterns = [
    path('', viewLoc, name="viewLoc"),
    path('addlocation/', newLocation, name='newLocation'),
    # path('<int:locationNo>/',)
]

server/server/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/auth/', include('users.urls')),
    path('api/location/', include('locations.urls')),
    path('api/ticket/', include('tickets.urls')),
    path('api/payment/', include('payment.urls')),
]

server/users/urls.py
from django.urls import path

from .views import (login, logout, private, refresh, register, reset_password,
                    resetpasssord, test)

urlpatterns = [
    path('login/', login, name='login'),
    path('register/', register),
    path('private/', private),
    path('refresh/', refresh),
    path('reset/<str:token>/<int:userId>/', reset_password),
    path('resetPassword/', resetpasssord),
    path('logout/', logout),
    path('test/<int:testNo>/', test),
]

server/locations/models.py
from django.db import models
from users.models import User

# Create your models here.


def image_directory_path(instance, fileName):
    return 'locationImages/{0}/{1}/{2}'.format(instance.name, instance.admin.id, fileName)


class Location(models.Model):
    name = models.CharField(max_length=50, unique=True, null=False)
    address = models.CharField(max_length=100, unique=True, null=False)
    description = models.CharField(max_length=200, null=False)
    admin = models.ForeignKey(User, on_delete=models.CASCADE)
    images = models.ImageField(upload_to=image_directory_path, max_length=100)
    status = models.BooleanField(null=False)

    def __str__(self) -> str:
        return self.name

server/locations/forms.py
# from django.forms import ModelForm
# from .models import location


# class locationForm(ModelForm):
#     class Meta:
#         model = location
#         fields = ['name', 'address', 'description',
#                   'admin', 'images', 'status']

server/locations/views.py
from django.shortcuts import render
from django.contrib import messages
from users.models import User
from rest_framework.decorators import api_view
from users.models import User
from .models import Location
# from rest_framework.response import Response
# from .forms import locationForm
# Create your views here.


@api_view(['GET', 'POST'])
def newLocation(request):
    if request.method == "POST":
        name = request.POST.get('locationName')
        address = request.POST.get('locationAddress')
        description = request.POST.get('locationDescription')
        adminusername = request.POST.get('locationAdmin')
        adminFlag = User.objects.filter(username=adminusername).exists()
        if (adminFlag == False):
            messages.error(
                request, "The username provided does not exist. Please enter correct UserName.")
            return render(request, 'locationform.html')
        else:
            admin = User.objects.get(username=adminusername)
            images = request.FILES.get('locationImg')
            try:
                status = request.POST['locationStatus']
                print("status ", status)
            except:
                status = False
                print("status ", status)

            newlocation = Location(name=name, address=address,
                                   description=description, admin=admin, images=images, status=status)
            newlocation.save()

            messages.success(
                request, "Location details have been submitted. We will verify and get back on the email of the Admin.")
            return render(request, 'locationform.html')

    else:
        return render(request, 'locationform.html')


@api_view(['GET'])
def viewLoc(request):
    loc = Location.objects.all()
    return render(request, 'index.html', {'locations': loc})

server/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Card</title>
    <!-- <link href="style.css" rel="stylesheet"> -->
    <style>
        body {
  background-color: #222;
}

a {
  text-decoration: none;
}

.card {
  width: 500px !important;
  background: #fff;
  transition: box-shadow 0.3s ease-in-out;
  box-shadow: 0 1px 2px 0 rgba(0, 0, 0, 0.15);
  margin: 30px;
}

/* Add box shadow to entire card on hover */
.card:hover {
  box-shadow: 0 1px 35px 0 rgba(0, 0, 0, 0.3);
}

/* Creates variation of card component in a wide format */
.card.card--wide {
  display: flex;
  justify-content: center;
  align-items: center;
  width: 768px;
}

.card__media {
  position: relative;
  width: 300px;
}

/* Adds transparent overlay over image. */
.card__media::before {
  content: "";
  display: block;
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  background: rgba(0, 0, 0, 0.3);
}

.card__media img {
  display: block;
  max-width: 100%;
  height: auto;
}

.card__date {
  position: absolute;
  right: 20px;
  top: 20px;
  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
  width: 70px;
  height: 70px;
  border-radius: 50%;
  background: #e74c3c;
  color: white;
  font-weight: bold;
}

.date--day {
  font-size: 20px;
  line-height: 1;
}

.date--month {
  font-size: 14px;
  line-height: 1;
  text-transform: uppercase;
}

.card__category {
  position: absolute;
  bottom: 0;
  left: 0;
  font-size: 14px;
  font-weight: bold;
  letter-spacing: 0.06em;
  display: inline-block;
  color: white;
  background: #e74c3c;
  text-align: center;
  padding: 5px 15px;
  text-transform: uppercase;
}

.card__content {
  padding: 0px 25px;
  color: #999999;
  transition: all 0.3s cubic-bezier(0.37, 0.75, 0.61, 1.05) 0s;
}

/* Changes padding on wide card */
.card--wide .card__content {
  /* padding: 20px 20px; */
  width: calc(100% - 300px);
}

/* By default we hide the excerpt on card long. */
.card__excerpt {
  max-height: 0;
  overflow: hidden;
  transition: max-height 0.3s ease-in-out;
}

/* Removes max-height on wide card */
.card--wide .card__excerpt {
  max-height: none;
}

/* On hover, we expand the excerpt container to show the text. */
.card:hover .card__excerpt {
  max-height: 300px;
}

.card__title {
  color: initial;
  margin: 0 0 10px;
  font-size: 20px;
}

.card__subtitle {
  color: #e74c3c;
  font-weight: 300;
}

.card__meta {
  color: #ccc;
  font-size: 14px;
}

.closed {
  background-color: #e74c3c !important;
  pointer-events:none;
}

.open {
  background-color: #079a01 !important;
}

.layout {
  display: flex;
  /* flex-direction: column; */
  /* justify-content: space-around; */
  align-items: flex-start;
  flex-wrap: wrap;
}

    </style>
    <script src="https://cdn.tailwindcss.com"></script>
</head>

<body>

    <div class="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap layout">

      {% if locations %}
      {% for location in locations %}
      {% if location.status %}
        <a href="http://localhost:8000/api/ticket/bookticket/{{location.pk}}/">
            <article class="card card--wide basis-1/3 flex-1">
                <div class="card__media">
                    <img src="https://res.cloudinary.com/dm6gcyihe/image/upload/v1/{{location.images}}"
                        alt="{{location.name}} image" />

                    <!-- Status agar false hoga to closed class lagana warna open lagana -->
                    {% if location.status %}
                    <div class="card__date open">
                        <span class="date--day">Open</span>
                        <!-- <span class="date--month">Mar</span> -->
                    </div>
                    {% else %}
                    <div class="card__date closed">
                      <span class="date--day">Closed</span>
                      <!-- <span class="date--month">Mar</span> -->
                    </div>
                    {% endif %}

                    <!-- <span class="card__category">Photos</span> -->
                </div>

                <div class="card__content">
                    <header class="card__header">
                        <!-- Tit le yha daal dena -->
                        <h2 class="card__title">{{location.name}}</h2>
                        <!-- <div class="card__subtitle">The city that never sleeps</div> -->
                    </header>
                    <!-- Description daal dena yha -->
                    <p class="card__excerpt">{{location.description}}</p>

                    <!-- <footer class="card__meta" role="contentinfo">
                                    <span class="card__post-date">Currently Open</span>
                                    <span class="card__comments">39 comments</span>
                                </footer> -->
                </div>
            </article>
        </a>
        {% else %}
        <a href="http://localhost:8000/api/ticket/bookticket/{{location.pk}}/" style="pointer-events:none;">
          <article class="card card--wide basis-1/3 flex-1">
              <div class="card__media">
                  <img src="https://res.cloudinary.com/dm6gcyihe/image/upload/v1/{{location.images}}"
                      alt="{{location.name}} image" />

                  <!-- Status agar false hoga to closed class lagana warna open lagana -->
                  {% if location.status %}
                  <div class="card__date open">
                      <span class="date--day">Open</span>
                      <!-- <span class="date--month">Mar</span> -->
                  </div>
                  {% else %}
                  <div class="card__date closed">
                    <span class="date--day">Closed</span>
                    <!-- <span class="date--month">Mar</span> -->
                  </div>
                  {% endif %}

                  <!-- <span class="card__category">Photos</span> -->
              </div>

              <div class="card__content">
                  <header class="card__header">
                      <!-- Tit le yha daal dena -->
                      <h2 class="card__title">{{location.name}}</h2>
                      <!-- <div class="card__subtitle">The city that never sleeps</div> -->
                  </header>
                  <!-- Description daal dena yha -->
                  <p class="card__excerpt">{{location.description}}</p>

                  <!-- <footer class="card__meta" role="contentinfo">
                                  <span class="card__post-date">Currently Open</span>
                                  <span class="card__comments">39 comments</span>
                              </footer> -->
              </div>
          </article>
      </a>
      {% endif %}
        {% endfor %}
        {% endif %}

    </div>

</body>

</html>

server/templates/locationform.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <style>
        .formdiv {
            margin: 50px;
            display: flex;
            flex-direction: column;
            /* align-items: center;
            justify-content: center; */
        }

        .success {
            font-size: larger;
            color: chartreuse;
        }

        .error {
            font-size: larger;
            color: red;
        }

        .messages {
            text-align: center;
        }
    </style>

</head>

<body class="bg-dark">
    <div class="formdiv">
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li type="none" class="{{ message.tags }}"> {{ message }} </li>
            {% endfor %}
        </ul>
        {% endif %}

        <form method="post" action="{% url 'locations:newLocation' %}" enctype="multipart/form-data">

            <div class="col-md-8" style="padding: 10px;color: aliceblue;">
                <label for="validationDefault01" class="form-label">Location Name</label>
                <input type="text" name="locationName" class="form-control" id="validationDefault01"
                    placeholder="Location Name" required>
            </div>
            <div class="col-md-12" style="padding: 10px;color: aliceblue;">
                <label for="validationDefault03" class="form-label">Address</label>
                <input type="text" name="locationAddress" class="form-control" id="validationDefault03"
                    placeholder="Address" required>
            </div>
            <div class="col-md-12" style="padding: 10px;color: aliceblue;">
                <label for="validationDefault02" class="form-label">Description</label>
                <input type="text" name="locationDescription" class="form-control" id="validationDefault02"
                    placeholder="Location Description" required>
            </div>
            {% csrf_token %}
            <div class="col-md-4" style="padding: 10px;color: aliceblue;">
                <label for="validationDefault01" class="form-label">Admin Username</label>
                <input type="text" name="locationAdmin" class="form-control" id="validationDefault01"
                    placeholder="Admin Username" required>
            </div>

            <div class="col-md-4" style="padding: 10px;color: aliceblue;">
                <label for="locationImg">Select image:</label>
                <input type="file" id="img" name="locationImg" accept="image/*" required>
            </div>
            <div class="form-check" style="padding: 10px;color: aliceblue;">
                <input name="locationStatus" class="form-check-input" type="checkbox" value="True" id="invalidCheck2">
                <label class="form-check-label" for="invalidCheck2">
                    Tick if the place is currently open for visitors
                </label>
            </div>
            <div class="col-12">
                <button class="btn btn-primary" type="submit">Submit form</button>
            </div>
        </form>

        <!-- <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
        </form>
        <div class="col-12">
            <button class="btn btn-primary" type="submit">Submit form</button>
        </div> -->

    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
</body>

</html>

server/templates/reset_password.html
<!-- <!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Reset Password</title>
</head>

<body>
  <form action="/api/auth/reset/{{token}}/{{userId}}/" method="post">
    {% csrf_token %}
    <input type="text" name="password1" placeholder="new password" />
    <br />
    <input type="text" name="password2" placeholder="confirm new password" />
    <br />
    <button type="submit">Reset Password</button>
  </form>
  </body>
  </html> -->
  
  
  
  {% load static %}
  <!DOCTYPE html>
  <html lang="en">
  
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reset Password</title>
    <link rel="stylesheet" href="{% static 'css/resetPasscss.css' %}" />
    <!-- <script src="{% static 'js/resetPass.js' %}"></script> -->
  </head>
  
  <body>
    <!-- <div class="overlay">
                                        <form action="/api/auth/reset/{{token}}/{{userId}}/" method="post">
                                          {% csrf_token %}
                                    
                                          <div class="con">
                                    
                                            <header class="head-form">
                                              <h2>Change Password</h2>
                                    
                                              <p>Enter your new password</p>
                                            </header>
                                            <br>
                                            <div class="field-set">
                                    
                                              <span class="input-item">
                                                <i class="fa fa-user-circle"></i>
                                              </span>
                                              <input type="password" placeholder="New Password" class="form-input" id="passOne" name="password1" required />
                                    
                                    
                                              <br>
                                    
                                              <span class="input-item">
                                                <i class="fa fa-key"></i>
                                              </span>
                                              <input type="password" placeholder="Confirm Password" id="passTwo" name="password2" required />
                                    
                                    
                                    
                                              <span>
                                                <i class="fa fa-eye" aria-hidden="true" type="button" id="eye"></i>
                                              </span>
                                    
                                              <div id="footer" class="incorrect">
                                                <center>
                                                  <h1 id="footerText">Filler text</h1>
                                                </center>
                                              </div>
                                    
                                    
                                              <br>
                                    
                                              <button class="log-in"> Change Password </button>
                                            </div>
                                    
                                    
                                            <div class="other">
                                    
                                              <i class="fa fa-user-plus" aria-hidden="true"></i>
                                              </button>
                                            </div>
                                    
                                            <!--   End Container  -->
    <!-- </div> -->
  
    <!-- End Form -->
    <!-- </div> -->
  
    <!-- <div id="container overlay">
                                          
                                              <div id="header">
                                                <center>
                                                  <h1>Change Password</h1>
                                                </center>
                                              </div>
                                              <div id="form">
                                                <input type="password" placeholder="New Password" id="passOne" />
                                                <input type="password" placeholder="Confirm Password" id="passTwo" />
                                              </div>
                                              <div id="footer" class="incorrect">
                                                <center>
                                                  <h1 id="footerText">Filler text</h1>
                                                </center>
                                              </div>
                                            </div> -->
  
  
    <div id="container">
  
      <div id="header">
        <form action="/api/auth/reset/{{token}}/{{userId}}/" method="post">
          {% csrf_token %}
          <center>
            <h1>Change Password</h1>
          </center>
          {% if messages %}
          <ul class="messages">
            {% for message in messages %}
            <li type="none" class="{{ message.tags }}"> {{ message }} </li>
            {% endfor %}
  
          </ul>
          {% endif %}
      </div>
      <div id="form">
        <input type="password" placeholder="New Password" id="passOne" name="password1" required />
        <input type="password" placeholder="Confirm Password" id="passTwo" name="password2" required />
      </div>
      <div id="footer" class="incorrect" style="display: flex; align-items: center;justify-content: center;">
        <button style="background: transparent;border: none;text-align: center;pointer-events: stroke;">
          <h1 id="footerText">Fields dont match</h1>
        </button>
      </div>
      </form>
    </div>
  
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <script>
      $(document).ready(function () {
        var passOne = $("#passOne").val();
        var passTwo = $("#passTwo").val();

        $("#footerText").html("Fields don't match");

        var checkAndChange = function () {
          if (passOne.length < 1) {
            if ($("#footer").hasClass("correct")) {
              $("#footer").removeClass("correct").addClass("incorrect");
              $("#footerText").html("They don't match");
            } else {
              $("#footerText").html("They don't match");
            }
          }
          else if ($("#footer").hasClass("incorrect")) {
            if (passOne == passTwo) {
              $("#footer").removeClass("incorrect").addClass("correct");
              $("#footerText").html("Continue");
            }
          }
          else {
            if (passOne != passTwo) {
              $("#footer").removeClass("correct").addClass("incorrect");
              $("#footerText").html("They don't match");
            }
          }
        }



        $("input").keyup(function () {
          var newPassOne = $("#passOne").val();
          var newPassTwo = $("#passTwo").val();

          passOne = newPassOne;
          passTwo = newPassTwo;

          checkAndChange();
        });
      });
    </script>
  </body>

</html>